# Generated by Django 3.2.6 on 2021-09-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
