# Generated by Django 3.2.6 on 2021-09-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210904_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.CharField(max_length=50),
        ),
    ]
